# ASF is a C# project with solution named ArchiSteamFarm.sln
language: csharp
solution: ArchiSteamFarm.sln

# Save bandwidth by limiting git clone to only last 10 commits
git:
  depth: 10

# Don't build other branches than master
# Sadly Travis doesn't support AppVeyor's "skip_branch_with_pr"
branches:
  only:
    - master

# This is our main build matrix
matrix:
# We can use fast finish, as we don't need to wait for all builds to mark it as failed/passed
  fast_finish: true
  allow_failures:
#   Mono is often broken, we might need to enable/disable allowing failures on as-needed basis
#   Currently we allow all Mono builds to fail, as it has serious problems, such as random SIGABRTs
#   This is decent because it allows us to track Mono builds and fix ASF if needed, while not going crazy over false alarms
#   Ref: https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/192428388#L2007-L2009
    - os: linux
    - os: osx
  include:
#   We're building ASF with Mono on latest versions of Linux and OS X
#   Ref: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
    - os: linux
      dist: trusty
      sudo: false
      mono: weekly
    - os: linux
      dist: trusty
      sudo: false
      mono: latest
    - os: osx
      osx_image: xcode8.3
      mono: weekly
    - os: osx
      osx_image: xcode8.3
      mono: latest

# Initialize our envsetup before building, we're adding some extra environment properties there
before_script:
  - source mono_envsetup.sh

# Push building notifications on Gitter
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df82484f12510c3f2516
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
