version: 1.0.{build}-{branch}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
clone_depth: 10
build:
  project: ArchiSteamFarm.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: 7z a -mx=9 -mfb=258 -mpass=15 %APPVEYOR_BUILD_FOLDER%\out\ASF.zip %APPVEYOR_BUILD_FOLDER%\out\ASF.exe %APPVEYOR_BUILD_FOLDER%\out\ASF-ConfigGenerator.exe %APPVEYOR_BUILD_FOLDER%\out\config
artifacts:
- path: out\ASF.zip
  name: ASF.zip
- path: out\ASF.exe
  name: ASF.exe
- path: out\ASF-Service.exe
  name: ASF-Service.exe
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/6cc89e76555ee263cc11
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
