"preserve_hierarchy": true
files:
  - source: /ArchiSteamFarm/Localization/Strings.resx
    translation: /ArchiSteamFarm/Localization/Strings.%locale%.resx
  - source: /ConfigGenerator/Localization/CGStrings.resx
    translation: /ConfigGenerator/Localization/CGStrings.%locale%.resx
